"""
migrations 004
"""

# Generated by Django 4.2.3 on 2024-12-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    classe de migração 004
    """

    dependencies = [
        ("users", "0003_cliente_funcionario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="plano",
            field=models.CharField(
                choices=[
                    ("Mensal", "Mensal"),
                    ("Semestral", "Semestral"),
                    ("Anual", "Anual"),
                ],
                default="Mensal",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("Gerente", "Gerente"),
                    ("Instrutor", "Instrutor"),
                    ("Recepcionista", "Recepcionista"),
                ],
                default="Instrutor",
                max_length=50,
            ),
        ),
    ]
