"""
Migrations 005
"""
# Generated by Django 4.2.3 on 2024-12-14 16:04

from django.db import migrations


class Migration(migrations.Migration):
    """
    classe de migração 005
    """

    dependencies = [
        ("users", "0004_alter_cliente_plano_alter_funcionario_cargo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="endereço",
            new_name="endereco",
        ),
    ]
