# Generated by Django 4.2.3 on 2024-12-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_usuario_delete_userprofileexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.usuario')),
                ('plano', models.CharField(max_length=50)),
                ('data_inicio_plano', models.DateField()),
                ('data_fim_plano', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('users.usuario',),
        ),
    ]
